import { ROUTES } from '../utils/constants';

export const routeConfig = {
  auth: [
    { path: ROUTES.LOGIN, label: 'Login' },
    { path: ROUTES.REGISTER, label: 'Register' },
    { path: ROUTES.FORGOT_PASSWORD, label: 'Forgot Password' },
    { path: ROUTES.RESET_PASSWORD, label: 'Reset Password' },
  ],
  dashboard: [
    { path: ROUTES.DASHBOARD, label: 'Dashboard' },
    { path: ROUTES.INBOX, label: 'Inbox' },
    { path: ROUTES.CONTACTS, label: 'Contacts' },
    { path: ROUTES.CONTACT_DETAILS, label: 'Contact Details' },
    { path: ROUTES.WHATSAPP_NUMBERS, label: 'WhatsApp Numbers' },
    { path: ROUTES.CONNECT_WHATSAPP, label: 'Connect WhatsApp' },
    { path: ROUTES.WHATSAPP_DETAILS, label: 'WhatsApp Details' },
    { path: ROUTES.TEMPLATES, label: 'Templates' },
    { path: ROUTES.CREATE_TEMPLATE, label: 'Create Template' },
    { path: ROUTES.TEMPLATE_DETAILS, label: 'Template Details' },
    { path: ROUTES.CAMPAIGNS, label: 'Campaigns' },
    { path: ROUTES.CREATE_CAMPAIGN, label: 'Create Campaign' },
    { path: ROUTES.CAMPAIGN_DETAILS, label: 'Campaign Details' },
    { path: ROUTES.AUTOMATIONS, label: 'Automations' },
    { path: ROUTES.CREATE_AUTOMATION, label: 'Create Automation' },
    { path: ROUTES.AI_DASHBOARD, label: 'AI Dashboard' },
    { path: ROUTES.AI_AGENT, label: 'AI Agent' },
    { path: ROUTES.AI_KNOWLEDGE_BASE, label: 'Knowledge Base' },
    { path: ROUTES.AI_SETTINGS, label: 'AI Settings' },
    { path: ROUTES.ANALYTICS, label: 'Analytics' },
    { path: ROUTES.BILLING, label: 'Billing' },
    { path: ROUTES.BILLING_PLANS, label: 'Plans' },
    { path: ROUTES.BILLING_INVOICES, label: 'Invoices' },
    { path: ROUTES.TEAM, label: 'Team' },
    { path: ROUTES.ROLES_PERMISSIONS, label: 'Roles & Permissions' },
    { path: ROUTES.ACCOUNT_SETTINGS, label: 'Account Settings' },
    { path: ROUTES.BUSINESS_PROFILE, label: 'Business Profile' },
    { path: ROUTES.SECURITY_SETTINGS, label: 'Security' },
  ],
  developer: [
    { path: ROUTES.DEVELOPERS_DASHBOARD, label: 'Developer Overview' },
    { path: ROUTES.DEVELOPERS_API_KEYS, label: 'API Keys' },
    { path: ROUTES.DEVELOPERS_WEBHOOKS, label: 'Webhooks' },
    { path: ROUTES.DEVELOPERS_API_LOGS, label: 'API Logs' },
    { path: ROUTES.DEVELOPERS_DOCS, label: 'Documentation' },
  ],
};
